spring:
  datasource:
    url: jdbc:sqlserver://sql-poc1.database.windows.net:1433;database=poc;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: poc
    password: dummy!12345
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9191


